
name: Deploy to GitHub Pages
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      uses: kibol-alert/frontend@dev
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: dev
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run deploy
